#!/usr/bin/env python3
"""Turn the college's Excel sheet into:
  1. assets/data/preview-data.js  - PUBLIC fields only (safe to publish)
  2. private/seed_distinguished.sql - full data incl. email/phone (never published; loaded into the database)
Uses only the Python standard library.
"""
import json, re, zipfile, sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "private" / "Entrepreneurs Details CPCA to Rakesh Jha.xlsx"
NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

# Sector grouping is an SCG classification for the directory filter (not in the sheet); alumni can edit it.
SECTORS = {
    "Seeds": [3, 6, 7, 8, 14, 15, 16, 22, 26, 32, 33, 34, 37, 39, 43, 47],
    "Crop Protection & Agrochemicals": [12, 13, 17, 21, 23, 36, 51],
    "Fertilizers & Agri Inputs": [1, 20, 24, 38, 40],
    "Bio & Organic Inputs": [11, 41, 44, 49, 50],
    "Food Processing & Supply Chain": [2, 4, 5, 19, 28],
    "Nursery & Tissue Culture": [9, 27, 30, 48],
    "Irrigation & Farm Machinery": [18, 29, 35],
    "Agri-tech & Services": [10, 42],
    "Consulting & Finance": [52],
    "Other Industries": [25, 31, 45, 46],
}
SECTOR_OF = {n: s for s, nums in SECTORS.items() for n in nums}


def read_rows():
    z = zipfile.ZipFile(XLSX)
    shared = ["".join(t.text or "" for t in si.iter(NS + "t"))
              for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall(NS + "si")]
    rows = []
    for row in ET.fromstring(z.read("xl/worksheets/sheet1.xml")).iter(NS + "row"):
        cells = {}
        for c in row.findall(NS + "c"):
            v = c.find(NS + "v")
            if v is None:
                continue
            col = re.match(r"[A-Z]+", c.get("r")).group()
            cells[col] = shared[int(v.text)] if c.get("t") == "s" else v.text
        if cells.get("A", "").strip().isdigit():
            rows.append(cells)
    return rows


def clean(s):
    return re.sub(r"[ \t]+", " ", (s or "").strip())


def to_int(s):
    s = clean(s)
    return int(s) if s.isdigit() else None


def parse(cells):
    n = int(cells["A"])
    name_lines = [clean(x) for x in cells["B"].split("\n") if clean(x)]
    company_lines = [clean(x) for x in cells.get("E", "").split("\n") if clean(x)]
    phone = re.sub(r"\s+", "", cells.get("H", ""))
    turnover = clean(cells.get("K", ""))
    return {
        "n": n,
        "full_name": name_lines[0],          # bracketed personal notes in the name cell are not published
        "headline": clean(cells.get("C", "")).rstrip("."),
        "batch_year": to_int(cells.get("D")),
        "company": company_lines[0] if company_lines else "",
        "company_about": " ".join(company_lines[1:]),
        "location": clean(cells.get("F", "")).rstrip("."),
        "sector": SECTOR_OF[n],
        "email": clean(cells.get("G", "")).lower(),
        "phone": phone,
        "year_established": to_int(cells.get("I")),
        "employees": to_int(cells.get("J")),
        "turnover": "" if turnover in ("-", "") else turnover.rstrip("."),
    }


def q(v):
    if v is None or v == "":
        return "null"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    people = [parse(r) for r in read_rows()]
    assert len(people) == 52, f"expected 52 alumni, found {len(people)}"
    emails = [p["email"] for p in people]
    assert len(set(emails)) == len(emails), "duplicate emails in sheet"

    public = [{k: p[k] for k in ("n", "full_name", "headline", "batch_year", "company",
                                 "company_about", "location", "sector", "year_established")}
              for p in people]
    out_js = ROOT / "assets" / "data" / "preview-data.js"
    out_js.write_text(
        "// Generated by scripts/build_seed.py from the college's sheet - PUBLIC fields only.\n"
        "// Used when the portal runs without its database (preview / double-click mode).\n"
        "window.CPCA_PREVIEW = " + json.dumps(public, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8")

    sql = ["-- Generated by scripts/build_seed.py. Contains personal data: NEVER publish or commit.",
           "begin;"]
    for p in people:
        sql.append(f"""
with prof as (
  insert into public.profiles (full_name, headline, location, sector, batch_year, status, is_distinguished)
  values ({q(p['full_name'])}, {q(p['headline'])}, {q(p['location'])}, {q(p['sector'])}, {q(p['batch_year'])}, 'approved', true)
  returning id
), priv as (
  insert into public.profile_private (profile_id, email, phone) select id, {q(p['email'])}, {q(p['phone'])} from prof
), seed as (
  insert into public.claim_seeds (profile_id, email) select id, {q(p['email'])} from prof
), edu as (
  insert into public.education (profile_id, institution, college, end_year, is_cpca)
  select id, 'Sardarkrushinagar Dantiwada Agricultural University (SDAU)', 'C. P. College of Agriculture', {q(p['batch_year'])}, true from prof
), comp as (
  insert into public.companies (profile_id, name, role, description, location, year_established)
  select id, {q(p['company'])}, 'Founder / Promoter', {q(p['company_about'])}, {q(p['location'])}, {q(p['year_established'])} from prof
  returning id
)
insert into public.company_stats (company_id, employees, turnover) select id, {q(p['employees'])}, {q(p['turnover'])} from comp;""")
    admin = (ROOT / "private" / "admin_email.txt").read_text().strip().lower()  # first administrator; kept out of the public repo
    sql.append(f"\ninsert into public.admin_emails (email) values ({q(admin)}) on conflict do nothing;")
    sql.append("commit;")
    (ROOT / "private" / "seed_distinguished.sql").write_text("\n".join(sql), encoding="utf-8")

    print(f"OK: {len(people)} alumni -> {out_js.relative_to(ROOT)} and private/seed_distinguished.sql")
    for p in people:
        if not re.fullmatch(r"[^@\s]+@[^@\s]+\.(com|in|co\.in|org|net)", p["email"]):
            print(f"  CHECK email  #{p['n']} {p['full_name']}: {p['email']}")
        if p["batch_year"] and p["year_established"] and p["year_established"] < p["batch_year"]:
            print(f"  CHECK years  #{p['n']} {p['full_name']}: passed out {p['batch_year']}, firm established {p['year_established']}")
    phones = {}
    for p in people:
        phones.setdefault(p["phone"], []).append(p["n"])
    for ph, ns in phones.items():
        if len(ns) > 1:
            print(f"  CHECK phone  same number {ph} on rows {ns}")


if __name__ == "__main__":
    sys.exit(main())
